apiVersion: v1
kind: Pod
metadata:
  name: db-pod
  labels:
    name: db-pod
    app: demo-voting-app
spec:
  containers:
  - name: postgres
    image: postgres:9.4
    env:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
    - containerPort: 5432